import { Post, StudentProfile } from "./types";

export const currentUserProfile: StudentProfile = {
  id: "prof-001",
  userId: "user-001",
  firstName: "Georgie",
  lastName: "Villar",
  username: "georgiedev",
  schoolId: "batstateu",
  schoolName: "Batangas State University - TNEU",
  course: "BS Computer Science",
  yearLevel: "3rd Year",
  bio: "Frontend engineer & student builder passionate about Next.js, clean UI systems, and hackathons. Building Nex Platform.",
  profileImage: "",
  skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Git"],
  interests: ["Hackathons", "Web Development", "AI Agents", "UI/UX"],
  githubUrl: "https://github.com",
  linkedinUrl: "https://linkedin.com",
  createdAt: "2026-09-01T08:00:00Z",
};

export const sampleSchools = [
  "Batangas State University - TNEU",
  "De La Salle University - Manila",
  "University of the Philippines Diliman",
  "Polytechnic University of the Philippines",
  "University of Santo Tomas",
  "Mapua University",
  "Ateneo de Manila University",
  "Far Eastern University - Tech",
  "University of Batangas",
  "First Asia Institute of Technology and Humanities",
];

export const sampleSkills = [
  "React",
  "Next.js",
  "TypeScript",
  "Python",
  "Tailwind CSS",
  "Node.js",
  "Supabase",
  "PostgreSQL",
  "Figma",
  "Flutter",
  "Docker",
  "FastAPI",
  "PyTorch",
  "C++",
  "Java",
  "IoT / ESP32",
];

export const sampleInterests = [
  "Hackathons",
  "AI & Machine Learning",
  "Web3 & Blockchain",
  "Mobile Apps",
  "Open Source",
  "Game Development",
  "Cloud & DevOps",
  "Robotics & Hardware",
  "Competitive Programming",
  "Startups & Innovation",
];

export const initialPosts: Post[] = [
  {
    id: "post-1",
    authorId: "user-002",
    author: {
      id: "user-002",
      name: "Marcus Aurelius Tan",
      username: "marcustan",
      avatar: "",
      school: "Batangas State University",
      course: "BS Information Technology",
    },
    title: "Looking for 1 Backend Dev (FastAPI / Supabase) for PacketHacks 2026!",
    content:
      "Hey everyone! We're forming a 4-person team for the upcoming PacketHacks 2026 student hackathon. Currently we have 2 frontend devs and 1 UI/UX designer. We need someone comfortable with Python/FastAPI or Node.js with Supabase DB. Drop a comment or reach out if you're interested in building a smart campus logistics app!",
    postType: "COLLABORATION",
    isAnonymous: false,
    upvotes: 18,
    commentsCount: 6,
    createdAt: "2026-09-29T14:30:00Z",
    tags: ["Hackathon", "PacketHacks", "FastAPI", "Teammates"],
    comments: [
      {
        id: "c-101",
        postId: "post-1",
        authorId: "user-003",
        author: {
          id: "user-003",
          name: "Chloe Santos",
          username: "chloecode",
          school: "DLSU",
          course: "BS CS",
        },
        content: "Sent you a message! I've built REST APIs with FastAPI and Supabase Auth before.",
        isAnonymous: false,
        createdAt: "2026-09-29T15:10:00Z",
        upvotes: 4,
      },
      {
        id: "c-102",
        postId: "post-1",
        authorId: "user-anon",
        author: {
          id: "user-anon",
          name: "Anonymous Student",
          username: "anonymous",
          school: "PUP",
          course: "BSIT",
        },
        content: "Is this open for 1st-year students? Familiar with Python and SQL basics.",
        isAnonymous: true,
        createdAt: "2026-09-29T16:05:00Z",
        upvotes: 2,
      },
    ],
  },
  {
    id: "post-2",
    authorId: "user-004",
    author: {
      id: "user-004",
      name: "Anonymous Student",
      username: "anonymous",
      avatar: "",
      school: "UST",
      course: "BS Computer Science",
    },
    title: "How do you handle state synchronization across multiple client devices without hitting Supabase free-tier limits?",
    content:
      "Working on a real-time IoT campus sensor dashboard for our capstone. We have 8 sensor nodes reporting temperature and crowd density every 5 seconds. Sometimes the realtime postgres websocket connection spikes. What caching strategies or batching mechanisms do you guys recommend?",
    postType: "QUESTION",
    isAnonymous: true,
    upvotes: 24,
    commentsCount: 4,
    createdAt: "2026-09-30T09:15:00Z",
    tags: ["Supabase", "IoT", "WebSockets", "Capstone"],
    comments: [
      {
        id: "c-201",
        postId: "post-2",
        authorId: "user-001",
        author: {
          id: "user-001",
          name: "Georgie Villar",
          username: "georgiedev",
          school: "BatStateU",
          course: "BSCS",
        },
        content:
          "Instead of writing every 5 seconds directly to PostgreSQL row triggers, consider aggregating in an edge worker or batch buffer (e.g. 30-sec windows) before inserting.",
        isAnonymous: false,
        createdAt: "2026-09-30T10:00:00Z",
        upvotes: 7,
      },
    ],
  },
  {
    id: "post-3",
    authorId: "user-005",
    author: {
      id: "user-005",
      name: "David Christian Reyes",
      username: "dreyes",
      avatar: "",
      school: "PUP Manila",
      course: "BS Computer Engineering",
    },
    title: "Showcase: 'AgriSense' — Low-cost Soil Nitrogen Monitoring Prototype built with ESP32 & Next.js",
    content:
      "Just finished our 3-week prototype for our agriculture engineering hackathon! It uses an optical sensor hooked to an ESP32 micro-controller, streaming telemetry to a Next.js 14 App Router dashboard with Tailwind and Recharts. Check out the demo repo on GitHub!",
    postType: "PROJECT",
    isAnonymous: false,
    upvotes: 31,
    commentsCount: 8,
    createdAt: "2026-09-30T16:45:00Z",
    tags: ["Showcase", "Hardware", "ESP32", "Nextjs"],
    comments: [],
  },
  {
    id: "post-4",
    authorId: "user-006",
    author: {
      id: "user-006",
      name: "Bea Patricia Cruz",
      username: "beacruz",
      avatar: "",
      school: "Mapua University",
      course: "BS Information Systems",
    },
    title: "Announcement: DOST-SEI Student Innovation Challenge 2026 Submissions are now open!",
    content:
      "Heads up to all student developers and engineering majors: The DOST-SEI national innovation challenge has opened applications for 2026 grants. Grants up to ₱100,000 for approved student startup prototypes. Deadline is on October 25.",
    postType: "OPPORTUNITY",
    isAnonymous: false,
    upvotes: 42,
    commentsCount: 5,
    createdAt: "2026-10-01T07:20:00Z",
    tags: ["Grants", "DOST", "StudentStartup", "Opportunity"],
    comments: [],
  },
];
