import {
  Post,
  StudentProfile,
  Project,
  CollaborationRequest,
  Opportunity,
  TechEvent,
  AppNotification,
} from "./types";

export const currentUserProfile: StudentProfile = {
  id: "prof-001",
  userId: "user-001",
  firstName: "Georgie",
  lastName: "Villar",
  username: "georgiedev",
  schoolId: "batstateu",
  schoolName: "Batangas State University - TNEU",
  course: "BS Computer Science",
  yearLevel: "3rd Year",
  bio: "Frontend engineer & student builder passionate about Next.js, clean UI systems, and hackathons. Building Nex Platform.",
  profileImage: "",
  skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Git"],
  interests: ["Hackathons", "Web Development", "AI Agents", "UI/UX"],
  githubUrl: "https://github.com",
  linkedinUrl: "https://linkedin.com",
  createdAt: "2026-09-01T08:00:00Z",
};

export const sampleSchools = [
  "Batangas State University - TNEU",
  "De La Salle University - Manila",
  "University of the Philippines Diliman",
  "Polytechnic University of the Philippines",
  "University of Santo Tomas",
  "Mapua University",
  "Ateneo de Manila University",
  "Far Eastern University - Tech",
  "University of Batangas",
  "First Asia Institute of Technology and Humanities",
];

export const sampleSkills = [
  "React",
  "Next.js",
  "TypeScript",
  "Python",
  "Tailwind CSS",
  "Node.js",
  "Supabase",
  "PostgreSQL",
  "Figma",
  "Flutter",
  "Docker",
  "FastAPI",
  "PyTorch",
  "C++",
  "Java",
  "IoT / ESP32",
];

export const sampleInterests = [
  "Hackathons",
  "AI & Machine Learning",
  "Web3 & Blockchain",
  "Mobile Apps",
  "Open Source",
  "Game Development",
  "Cloud & DevOps",
  "Robotics & Hardware",
  "Competitive Programming",
  "Startups & Innovation",
];

export const initialPosts: Post[] = [
  {
    id: "post-1",
    authorId: "user-002",
    author: {
      id: "user-002",
      name: "Marcus Aurelius Tan",
      username: "marcustan",
      avatar: "",
      school: "Batangas State University",
      course: "BS Information Technology",
    },
    title: "Looking for 1 Backend Dev (FastAPI / Supabase) for PacketHacks 2026!",
    content:
      "Hey everyone! We're forming a 4-person team for the upcoming PacketHacks 2026 student hackathon. Currently we have 2 frontend devs and 1 UI/UX designer. We need someone comfortable with Python/FastAPI or Node.js with Supabase DB. Drop a comment or reach out if you're interested in building a smart campus logistics app!",
    postType: "COLLABORATION",
    isAnonymous: false,
    upvotes: 18,
    commentsCount: 6,
    createdAt: "2026-09-29T14:30:00Z",
    tags: ["Hackathon", "PacketHacks", "FastAPI", "Teammates"],
    comments: [
      {
        id: "c-101",
        postId: "post-1",
        authorId: "user-003",
        author: {
          id: "user-003",
          name: "Chloe Santos",
          username: "chloecode",
          school: "DLSU",
          course: "BS CS",
        },
        content: "Sent you a message! I've built REST APIs with FastAPI and Supabase Auth before.",
        isAnonymous: false,
        createdAt: "2026-09-29T15:10:00Z",
        upvotes: 4,
      },
      {
        id: "c-102",
        postId: "post-1",
        authorId: "user-anon",
        author: {
          id: "user-anon",
          name: "Anonymous Student",
          username: "anonymous",
          school: "PUP",
          course: "BSIT",
        },
        content: "Is this open for 1st-year students? Familiar with Python and SQL basics.",
        isAnonymous: true,
        createdAt: "2026-09-29T16:05:00Z",
        upvotes: 2,
      },
    ],
  },
  {
    id: "post-2",
    authorId: "user-004",
    author: {
      id: "user-004",
      name: "Anonymous Student",
      username: "anonymous",
      avatar: "",
      school: "UST",
      course: "BS Computer Science",
    },
    title: "How do you handle state synchronization across multiple client devices without hitting Supabase free-tier limits?",
    content:
      "Working on a real-time IoT campus sensor dashboard for our capstone. We have 8 sensor nodes reporting temperature and crowd density every 5 seconds. Sometimes the realtime postgres websocket connection spikes. What caching strategies or batching mechanisms do you guys recommend?",
    postType: "QUESTION",
    isAnonymous: true,
    upvotes: 24,
    commentsCount: 4,
    createdAt: "2026-09-30T09:15:00Z",
    tags: ["Supabase", "IoT", "WebSockets", "Capstone"],
    comments: [
      {
        id: "c-201",
        postId: "post-2",
        authorId: "user-001",
        author: {
          id: "user-001",
          name: "Georgie Villar",
          username: "georgiedev",
          school: "BatStateU",
          course: "BSCS",
        },
        content:
          "Instead of writing every 5 seconds directly to PostgreSQL row triggers, consider aggregating in an edge worker or batch buffer (e.g. 30-sec windows) before inserting.",
        isAnonymous: false,
        createdAt: "2026-09-30T10:00:00Z",
        upvotes: 7,
      },
    ],
  },
  {
    id: "post-3",
    authorId: "user-005",
    author: {
      id: "user-005",
      name: "David Christian Reyes",
      username: "dreyes",
      avatar: "",
      school: "PUP Manila",
      course: "BS Computer Engineering",
    },
    title: "Showcase: 'AgriSense' — Low-cost Soil Nitrogen Monitoring Prototype built with ESP32 & Next.js",
    content:
      "Just finished our 3-week prototype for our agriculture engineering hackathon! It uses an optical sensor hooked to an ESP32 micro-controller, streaming telemetry to a Next.js 14 App Router dashboard with Tailwind and Recharts. Check out the demo repo on GitHub!",
    postType: "PROJECT",
    isAnonymous: false,
    upvotes: 31,
    commentsCount: 8,
    createdAt: "2026-09-30T16:45:00Z",
    tags: ["Showcase", "Hardware", "ESP32", "Nextjs"],
    comments: [],
  },
  {
    id: "post-4",
    authorId: "user-006",
    author: {
      id: "user-006",
      name: "Bea Patricia Cruz",
      username: "beacruz",
      avatar: "",
      school: "Mapua University",
      course: "BS Information Systems",
    },
    title: "Announcement: DOST-SEI Student Innovation Challenge 2026 Submissions are now open!",
    content:
      "Heads up to all student developers and engineering majors: The DOST-SEI national innovation challenge has opened applications for 2026 grants. Grants up to ₱100,000 for approved student startup prototypes. Deadline is on October 25.",
    postType: "OPPORTUNITY",
    isAnonymous: false,
    upvotes: 42,
    commentsCount: 5,
    createdAt: "2026-10-01T07:20:00Z",
    tags: ["Grants", "DOST", "StudentStartup", "Opportunity"],
    comments: [],
  },
];

export const initialProjects: Project[] = [
  {
    id: "proj-1",
    ownerId: "user-001",
    owner: {
      id: "user-001",
      name: "Georgie Villar",
      username: "georgiedev",
      school: "Batangas State University - TNEU",
      course: "BS Computer Science",
    },
    name: "Nex Community Platform",
    description:
      "A student-driven web platform designed for tech builders across Philippine universities to communicate, recruit hackathon teammates, share project showcases, and discover tech opportunities.",
    category: "Web & Developer Tools",
    status: "DEVELOPMENT",
    repositoryUrl: "https://github.com/FerosC101/Nex-Platform",
    demoUrl: "https://nex-network.vercel.app",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase"],
    createdAt: "2026-09-24T00:00:00Z",
    updatedAt: "2026-10-01T08:00:00Z",
    members: [
      {
        id: "mem-1",
        projectId: "proj-1",
        userId: "user-001",
        user: {
          id: "user-001",
          name: "Georgie Villar",
          username: "georgiedev",
          school: "BatStateU",
          course: "BSCS",
        },
        role: "Frontend Lead",
        joinedAt: "2026-09-24T00:00:00Z",
      },
      {
        id: "mem-2",
        projectId: "proj-1",
        userId: "user-lead",
        user: {
          id: "user-lead",
          name: "Vince Anjo Villar",
          username: "vincevillar",
          school: "BatStateU",
          course: "BSCS",
        },
        role: "Project Lead",
        joinedAt: "2026-09-24T00:00:00Z",
      },
    ],
    collaborationRequests: [
      {
        id: "collab-1",
        creatorId: "user-001",
        projectId: "proj-1",
        title: "Seeking 1 UI/UX Designer & 1 Supabase Backend Developer",
        description:
          "We are polishing Phase 2 of the platform. Looking for a designer comfortable with Figma tokens and a backend developer with Supabase Auth & RLS experience.",
        skillsRequired: ["Figma", "Supabase", "PostgreSQL", "Tailwind CSS"],
        status: "OPEN",
        createdAt: "2026-09-30T10:00:00Z",
        applicationsCount: 3,
      },
    ],
  },
  {
    id: "proj-2",
    ownerId: "user-005",
    owner: {
      id: "user-005",
      name: "David Christian Reyes",
      username: "dreyes",
      school: "PUP Manila",
      course: "BS Computer Engineering",
    },
    name: "AgriSense — Low-cost Soil Telemetry Node",
    description:
      "IoT sensor array using ESP32 to monitor soil nitrogen, phosphorus, and moisture in real time, transmitting telemetry to a Next.js web dashboard.",
    category: "Hardware & IoT",
    status: "PROTOTYPE",
    repositoryUrl: "https://github.com/example/agrisense-iot",
    tags: ["ESP32", "C++", "Next.js", "FastAPI"],
    createdAt: "2026-09-15T00:00:00Z",
    updatedAt: "2026-09-30T16:00:00Z",
    members: [
      {
        id: "mem-3",
        projectId: "proj-2",
        userId: "user-005",
        user: {
          id: "user-005",
          name: "David Christian Reyes",
          username: "dreyes",
          school: "PUP Manila",
          course: "BS Computer Engineering",
        },
        role: "Hardware & Firmware Lead",
        joinedAt: "2026-09-15T00:00:00Z",
      },
    ],
    collaborationRequests: [
      {
        id: "collab-2",
        creatorId: "user-005",
        projectId: "proj-2",
        title: "Looking for Frontend Developer to build Sensor Charts",
        description:
          "Need a React/Next.js developer to integrate Recharts or Chart.js for real-time sensor graphs.",
        skillsRequired: ["React", "Chart.js", "Tailwind CSS"],
        status: "OPEN",
        createdAt: "2026-09-28T09:00:00Z",
        applicationsCount: 1,
      },
    ],
  },
  {
    id: "proj-3",
    ownerId: "user-003",
    owner: {
      id: "user-003",
      name: "Chloe Santos",
      username: "chloecode",
      school: "De La Salle University",
      course: "BS Computer Science",
    },
    name: "StudySync — University Peer Tutoring Hub",
    description:
      "Mobile-first web application connecting senior engineering students with underclassmen seeking tutorial sessions in Calculus, Algorithms, and Data Structures.",
    category: "EdTech & Mobile",
    status: "PLANNING",
    repositoryUrl: "https://github.com/example/studysync-app",
    tags: ["Flutter", "Dart", "Firebase"],
    createdAt: "2026-09-20T00:00:00Z",
    updatedAt: "2026-09-29T12:00:00Z",
    members: [
      {
        id: "mem-4",
        projectId: "proj-3",
        userId: "user-003",
        user: {
          id: "user-003",
          name: "Chloe Santos",
          username: "chloecode",
          school: "DLSU",
          course: "BS CS",
        },
        role: "Lead Mobile Developer",
        joinedAt: "2026-09-20T00:00:00Z",
      },
    ],
    collaborationRequests: [
      {
        id: "collab-3",
        creatorId: "user-003",
        projectId: "proj-3",
        title: "Need 1 Backend Developer (Node.js / Express)",
        description:
          "Looking for a backend collaborator to design the session booking REST API and database schemas.",
        skillsRequired: ["Node.js", "Express", "PostgreSQL"],
        status: "OPEN",
        createdAt: "2026-09-29T10:00:00Z",
        applicationsCount: 2,
      },
    ],
  },
  {
    id: "proj-4",
    ownerId: "user-002",
    owner: {
      id: "user-002",
      name: "Marcus Aurelius Tan",
      username: "marcustan",
      school: "Batangas State University",
      course: "BS Information Technology",
    },
    name: "CampusLogix — Smart Transit Tracker",
    description:
      "Automated campus shuttle and transport tracking system with estimated time of arrival (ETA) predictions for university commuters.",
    category: "Smart Campus & Transportation",
    status: "IDEA",
    tags: ["Python", "FastAPI", "Docker", "PostgreSQL"],
    createdAt: "2026-09-28T00:00:00Z",
    updatedAt: "2026-10-01T06:00:00Z",
    members: [
      {
        id: "mem-5",
        projectId: "proj-4",
        userId: "user-002",
        user: {
          id: "user-002",
          name: "Marcus Aurelius Tan",
          username: "marcustan",
          school: "BatStateU",
          course: "BSIT",
        },
        role: "Project Initiator",
        joinedAt: "2026-09-28T00:00:00Z",
      },
    ],
    collaborationRequests: [
      {
        id: "collab-4",
        creatorId: "user-002",
        projectId: "proj-4",
        title: "PacketHacks 2026 Team: Need 1 Mobile Dev & 1 Backend Dev",
        description:
          "Forming a student team for PacketHacks 2026. Looking for builders enthusiastic about GPS telemetry and mapping.",
        skillsRequired: ["Python", "Flutter", "Leaflet / Maps"],
        status: "OPEN",
        createdAt: "2026-09-29T14:30:00Z",
        applicationsCount: 4,
      },
    ],
  },
];

// ==========================================
// Phase 3: Opportunities Dataset
// ==========================================

export const initialOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    title: "DOST-SEI Student Innovation Challenge 2026",
    organization: "Department of Science and Technology (DOST-SEI)",
    type: "GRANT",
    description:
      "National innovation grant awarded to undergraduate engineering and computer science students developing working hardware or software prototypes that address sustainable community development.",
    locationType: "HYBRID",
    location: "Metro Manila / Nationwide",
    deadline: "2026-10-25T23:59:59Z",
    eligibility: "Enrolled Undergraduate Students (Teams of 3-5)",
    applicationUrl: "https://www.sei.dost.gov.ph",
    reward: "₱100,000 Prototype Seed Grant",
    tags: ["Grant", "DOST", "Government", "Hardware/IoT", "Sustainability"],
    createdAt: "2026-09-15T08:00:00Z",
    featured: true,
  },
  {
    id: "opp-2",
    title: "NASA Space Apps Challenge 2026 — Manila Edition",
    organization: "NASA Space Apps Manila",
    type: "HACKATHON",
    description:
      "Global hackathon inviting student coders, scientists, and designers to solve real-world problems on Earth and in space using NASA's open-source datasets.",
    locationType: "HYBRID",
    location: "DLSU Manila & Virtual",
    deadline: "2026-10-18T18:00:00Z",
    eligibility: "Open to All College & High School Students",
    applicationUrl: "https://www.spaceappschallenge.org",
    reward: "₱150,000 Prize Pool + Global Judging Nomination",
    tags: ["Hackathon", "Data Science", "SpaceTech", "Global"],
    createdAt: "2026-09-20T10:00:00Z",
    featured: true,
  },
  {
    id: "opp-3",
    title: "Google Solution Challenge Philippines 2026",
    organization: "Google Developer Student Clubs (GDSC)",
    type: "COMPETITION",
    description:
      "Annual competition for university students to build solutions for one or more of the United Nations 17 Sustainable Development Goals using Google technologies.",
    locationType: "ONLINE",
    location: "Virtual",
    deadline: "2026-11-15T23:59:59Z",
    eligibility: "Active GDSC Members & University Students",
    applicationUrl: "https://developers.google.com/community/gdsc-solution-challenge",
    reward: "$10,000 USD Grant + Google Engineers Mentorship",
    tags: ["Google", "AI", "Cloud", "SDG", "International"],
    createdAt: "2026-09-22T09:00:00Z",
    featured: true,
  },
  {
    id: "opp-4",
    title: "GCash NextGen Software Engineering Intern (2026 Cohort)",
    organization: "Mynt (Globe Fintech Innovations)",
    type: "INTERNSHIP",
    description:
      "6-month paid internship program for 3rd and 4th-year tech students. Work directly alongside production squads building high-concurrency microservices, payment gateways, and security pipelines.",
    locationType: "HYBRID",
    location: "BGC, Taguig City (2 Days Onsite / 3 Days Remote)",
    deadline: "2026-10-31T17:00:00Z",
    eligibility: "3rd & 4th Year BS CS, IT, ECE Students",
    applicationUrl: "https://www.gcash.com/careers",
    reward: "Paid Internship + Pre-Placement Job Offer (PPO)",
    tags: ["Fintech", "Next.js", "Java", "Kubernetes", "Paid"],
    createdAt: "2026-09-25T11:00:00Z",
  },
  {
    id: "opp-5",
    title: "DevCon Student Tech Fellowship — Batch 5",
    organization: "DevCon Philippines Foundation",
    type: "FELLOWSHIP",
    description:
      "Intensive 10-week accelerated fellowship pairing promising student developers with Silicon Valley and Southeast Asia engineering leads for hands-on open-source architecture.",
    locationType: "ONLINE",
    location: "Virtual / Discord & GitHub",
    deadline: "2026-11-05T23:59:59Z",
    eligibility: "Filipino Tech Students with at least 1 public GitHub repo",
    applicationUrl: "https://devcon.ph/fellowship",
    reward: "₱30,000 Learning Grant + 1-on-1 Mentorship",
    tags: ["Open Source", "Mentorship", "Fellowship", "Career"],
    createdAt: "2026-09-27T13:00:00Z",
  },
  {
    id: "opp-6",
    title: "Accenture Philippines Student Innovation Hackfest",
    organization: "Accenture Philippines",
    type: "HACKATHON",
    description:
      "48-hour collaborative hackathon focused on Enterprise Generative AI, Cloud Resilience, and Cybersecurity prototypes for university builders.",
    locationType: "ONSITE",
    location: "Accenture Innovation Hub, Makati City",
    deadline: "2026-10-22T20:00:00Z",
    eligibility: "Collegiate Teams of 2 to 4 Students",
    applicationUrl: "https://www.accenture.com/ph-en/careers",
    reward: "₱80,000 Cash Prize + Fast-Track Associate Interviews",
    tags: ["AI", "Enterprise", "Hackathon", "Networking"],
    createdAt: "2026-09-28T15:30:00Z",
  },
];

// ==========================================
// Phase 3: Events Dataset
// ==========================================

export const initialEvents: TechEvent[] = [
  {
    id: "evt-1",
    title: "Building Scalable Full-Stack Apps with Next.js 15 & Supabase",
    description:
      "A deep dive workshop covering Server Actions, Turbopack, Row-Level Security (RLS), and database webhooks tailored for student builders building hackathon MVPs.",
    type: "WORKSHOP",
    date: "2026-10-10",
    startTime: "14:00",
    endTime: "17:00",
    locationType: "ONLINE",
    location: "Zoom Video Conference & Discord Stream",
    organizer: "Nex Engineering Guild",
    speaker: {
      name: "Sophia Dela Cruz",
      role: "Staff Engineer & Community Contributor",
      organization: "Vercel Ecosystem / BatStateU Alum",
    },
    capacity: 150,
    registeredCount: 118,
    tags: ["Next.js", "Supabase", "TypeScript", "Architecture"],
    bannerGradient: "from-cyan-900/60 via-card to-background",
    agenda: [
      { time: "14:00 - 14:20", title: "Keynote: Architectural Evolution of Next.js App Router" },
      { time: "14:20 - 15:30", title: "Hands-on Lab: Server Components & Supabase RLS in Practice" },
      { time: "15:30 - 16:30", title: "Live Build: Real-time Collaboration Engine with PostgreSQL Webhooks" },
      { time: "16:30 - 17:00", title: "Q&A and Student Code Review Session" },
    ],
  },
  {
    id: "evt-2",
    title: "DOST-SEI Innovation Challenge 2026: Official Pitch & Guidelines Kickoff",
    description:
      "Exclusive briefing and proposal writing orientation for student teams aiming for the ₱100,000 grant. Learn directly from regional technical evaluators.",
    type: "HACKATHON_KICKOFF",
    date: "2026-10-14",
    startTime: "10:00",
    endTime: "12:00",
    locationType: "HYBRID",
    location: "BatStateU Main Campus Auditorium & YouTube Live",
    organizer: "DOST Region IV-A & Nex Network",
    speaker: {
      name: "Engr. Ronald Morales",
      role: "Senior Science Research Specialist",
      organization: "DOST-SEI",
    },
    capacity: 200,
    registeredCount: 174,
    tags: ["DOST", "Grants", "Pitching", "Guidelines"],
    bannerGradient: "from-amber-900/50 via-card to-background",
    agenda: [
      { time: "10:00 - 10:30", title: "Opening Remarks: 2026 Grant Scope & Priorities" },
      { time: "10:30 - 11:15", title: "Evaluating Rubrics: From Idea to Working Hardware Prototype" },
      { time: "11:15 - 12:00", title: "Open Consultation for Student Major Projects & Theses" },
    ],
  },
  {
    id: "evt-3",
    title: "Low-Power IoT Prototyping: ESP32, MQTT & Real-time Webhooks",
    description:
      "Hands-on sensor telemetry workshop. Connect analog temperature and optical sensors to microcontroller boards and stream readings to web dashboards.",
    type: "WORKSHOP",
    date: "2026-10-20",
    startTime: "13:00",
    endTime: "16:30",
    locationType: "ONSITE",
    location: "MakerLab Room 402, BatStateU Alangilan Campus",
    organizer: "Nex Hardware Guild",
    speaker: {
      name: "David Christian Reyes",
      role: "Hardware & Embedded Systems Lead",
      organization: "AgriSense IoT / PUP Manila",
    },
    capacity: 40,
    registeredCount: 35,
    tags: ["IoT", "ESP32", "Hardware", "MQTT"],
    bannerGradient: "from-emerald-900/50 via-card to-background",
    agenda: [
      { time: "13:00 - 13:45", title: "Microcontroller Setup & Flashing MicroPython / C++" },
      { time: "13:45 - 15:15", title: "Interfacing Soil & Temperature Sensors with MQTT Broker" },
      { time: "15:15 - 16:30", title: "Dashboard Integration: Ingesting Telemetry into Next.js" },
    ],
  },
  {
    id: "evt-4",
    title: "Nex Builder Meetup: University Showcases & Lightning Talks",
    description:
      "Casual student demo night. 5 student startup teams will deliver 5-minute rapid demos of their live prototypes followed by networking and pizza.",
    type: "CAMPUS_MEETUP",
    date: "2026-10-28",
    startTime: "15:00",
    endTime: "19:00",
    locationType: "ONSITE",
    location: "Innovation Center Ground Floor, BatStateU Pablo Borbon",
    organizer: "Nex Community Platform",
    speaker: {
      name: "Georgie Villar & Student Creators",
      role: "Core Builders",
      organization: "Nex Network",
    },
    capacity: 80,
    registeredCount: 64,
    tags: ["Networking", "DemoNight", "Showcase", "Community"],
    bannerGradient: "from-purple-900/50 via-card to-background",
    agenda: [
      { time: "15:00 - 15:30", title: "Check-in, Badges & Welcoming" },
      { time: "15:30 - 17:00", title: "5 x 10-Minute University Project Demos" },
      { time: "17:00 - 17:45", title: "Builder Panel: Navigating Hackathons as Undergrads" },
      { time: "17:45 - 19:00", title: "Open Teammate Networking & Prototype Testing" },
    ],
  },
];

// ==========================================
// Phase 3: Notifications Dataset
// ==========================================

export const initialNotifications: AppNotification[] = [
  {
    id: "notif-1",
    userId: "user-001",
    type: "COLLABORATION_REQUEST",
    title: "New Collaborator Application",
    message: "Marcus Aurelius Tan applied to join 'Nex Community Platform' as Full-stack Contributor.",
    link: "/projects/proj-1",
    isRead: false,
    createdAt: "2026-10-02T09:45:00Z",
  },
  {
    id: "notif-2",
    userId: "user-001",
    type: "COMMENT_REPLY",
    title: "New Reply on Your Post",
    message: "Bea Patricia Cruz replied: 'Consider aggregating in an edge worker before inserting.'",
    link: "/community/post-1",
    isRead: false,
    createdAt: "2026-10-02T08:15:00Z",
  },
  {
    id: "notif-3",
    userId: "user-001",
    type: "OPPORTUNITY_DEADLINE",
    title: "Opportunity Deadline Approaching",
    message: "NASA Space Apps Challenge Manila registration closes in 6 days (Oct 18).",
    link: "/opportunities",
    isRead: false,
    createdAt: "2026-10-02T05:30:00Z",
  },
  {
    id: "notif-4",
    userId: "user-001",
    type: "EVENT_REMINDER",
    title: "Registered Event Reminder",
    message: "Upcoming: 'Building Scalable Full-Stack Apps with Next.js 15 & Supabase' starts on Oct 10.",
    link: "/events/evt-1",
    isRead: true,
    createdAt: "2026-10-01T14:00:00Z",
  },
  {
    id: "notif-5",
    userId: "user-001",
    type: "UPVOTE_MILESTONE",
    title: "Trending Post Milestone",
    message: "Your prototype showcase 'Nex Community Platform' reached 30+ student upvotes!",
    link: "/community/post-3",
    isRead: true,
    createdAt: "2026-09-30T19:00:00Z",
  },
];

